name: Rust & Anchor tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  run-anchor-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Solana
        run: |
          sudo apt-get update
          SOLANA_VERSION=1.14.16
          sh -c "$(curl -sSfL https://release.solana.com/v$SOLANA_VERSION/install)"
          echo "$HOME/.local/share/solana/install/releases/$SOLANA_VERSION/solana-release/bin" >> $GITHUB_PATH

      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked
          avm install 0.27.0
          avm use 0.27.0
          echo "$HOME/.avm/bin" >> $GITHUB_PATH

      - name: Run tests
        run: anchor test

